### PR TITLE
Fix Dugite Bump

### PR DESCRIPTION
**Pull request by confused-Techie**
Alright so seems on PR #2 those changes had targeted `bump-keytar` not `master`.

Attempting to cherry pick the commit didn't totally work, as the changes that were present in the `package-lock.json` were to far from our current branch that a mix of dependency peer conflicts, and merge conflicts, caused the final result leaving a broken package.json.

So I cherry picked what I could and otherwise made the same changes manually that were present originally. 

From there I also went ahead and bumped the version one last time, and ran `npm install` to ensure our changes were reflected on the `package-lock.json` and that the file indeed was error free.

I'll leave this up for a short time, but as the previous PR was merged without issue, I may go ahead and merge this one if no reviews are present.

Thanks for anyone taking a look.

### CODE REVIEW

**Comment by benonymus** [comment]
We need the other package update from that pr too for apple silicon to work: 
"electron-mksnapshot": "^12.0.0", 
https://github.com/pulsar-edit/github/pull/2/files
11 and above supports apple silicon: https://github.com/electron/mksnapshot/releases/tag/v11.0.1
@confused-Techie

**Comment by confused-Techie** [comment]
> We need the other package update from that pr too for apple silicon to work: "electron-mksnapshot": "^12.0.0", https://github.com/pulsar-edit/github/pull/2/files 11 and above supports apple silicon: https://github.com/electron/mksnapshot/releases/tag/v11.0.1 @confused-Techie

Ahh I see, well it seems when trying to upgrade to `electron-mksnapshot@12.0.0` by using `npm install electron-mksnapshot@12.0.0` I get the following output:

```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: eslint-config-fbjs-opensource@1.0.0
npm ERR! Found: eslint@6.8.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@">=3.0.0" from eslint-plugin-babel@4.1.2
npm ERR!   node_modules/eslint-plugin-babel
npm ERR!     eslint-plugin-babel@"^4.0.1" from eslint-config-fbjs-opensource@1.0.0
npm ERR!     node_modules/eslint-config-fbjs-opensource
npm ERR!       dev eslint-config-fbjs-opensource@"1.0.0" from the root project
npm ERR!   peer eslint@">=2.0.0" from eslint-plugin-flowtype@2.50.3
npm ERR!   node_modules/eslint-plugin-flowtype
npm ERR!     eslint-plugin-flowtype@"^2.30.0" from eslint-config-fbjs-opensource@1.0.0
npm ERR!     node_modules/eslint-config-fbjs-opensource
npm ERR!       dev eslint-config-fbjs-opensource@"1.0.0" from the root project
npm ERR!   3 more (eslint-plugin-jsx-a11y, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^3.0.0" from eslint-config-fbjs-opensource@1.0.0
npm ERR! node_modules/eslint-config-fbjs-opensource
npm ERR!   dev eslint-config-fbjs-opensource@"1.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: eslint@3.19.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@"^3.0.0" from eslint-config-fbjs-opensource@1.0.0
npm ERR!   node_modules/eslint-config-fbjs-opensource
npm ERR!     dev eslint-config-fbjs-opensource@"1.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\<user>\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<user>\AppData\Local\npm-cache\_logs\2022-12-02T02_37_44_862Z-debug-0.log
```

So it looks like that upgrade was only possible from the `node-keytar` branch. @mauricioszabo whats the possibility of merging that whole branch with `master` here? Otherwise I'll try to take a look at what changes actually made this possible

**Comment by confused-Techie** [comment]
So further on this, looks like for that branch the only unpublished changes are an update to `keytar`.

Meaning we need `keytar`, `electron-mksnapshot`, and `dugite`.

But this does result on peer dep conflicts on trying any of the following. It does seem almost all the conflicts are from `eslint` so maybe we should just force the upgrades and not care to much about `eslint`? Since it's only used when running `npm run lint`

**Comment by confused-Techie** [comment]
Alright @benonymus bumped `electron-mksnapshot` as well using `npm install electron-mksnapshot@12.0.0 --force`

**Comment by benonymus** [comment]
> > We need the other package update from that pr too for apple silicon to work: "electron-mksnapshot": "^12.0.0", https://github.com/pulsar-edit/github/pull/2/files 11 and above supports apple silicon: https://github.com/electron/mksnapshot/releases/tag/v11.0.1 @confused-Techie
> 
> Ahh I see, well it seems when trying to upgrade to `electron-mksnapshot@12.0.0` by using `npm install electron-mksnapshot@12.0.0` I get the following output:
> 
> ```
> npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE could not resolve
> npm ERR!
> npm ERR! While resolving: eslint-config-fbjs-opensource@1.0.0
> npm ERR! Found: eslint@6.8.0
> npm ERR! node_modules/eslint
> npm ERR!   peer eslint@">=3.0.0" from eslint-plugin-babel@4.1.2
> npm ERR!   node_modules/eslint-plugin-babel
> npm ERR!     eslint-plugin-babel@"^4.0.1" from eslint-config-fbjs-opensource@1.0.0
> npm ERR!     node_modules/eslint-config-fbjs-opensource
> npm ERR!       dev eslint-config-fbjs-opensource@"1.0.0" from the root project
> npm ERR!   peer eslint@">=2.0.0" from eslint-plugin-flowtype@2.50.3
> npm ERR!   node_modules/eslint-plugin-flowtype
> npm ERR!     eslint-plugin-flowtype@"^2.30.0" from eslint-config-fbjs-opensource@1.0.0
> npm ERR!     node_modules/eslint-config-fbjs-opensource
> npm ERR!       dev eslint-config-fbjs-opensource@"1.0.0" from the root project
> npm ERR!   3 more (eslint-plugin-jsx-a11y, ...)
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer eslint@"^3.0.0" from eslint-config-fbjs-opensource@1.0.0
> npm ERR! node_modules/eslint-config-fbjs-opensource
> npm ERR!   dev eslint-config-fbjs-opensource@"1.0.0" from the root project
> npm ERR!
> npm ERR! Conflicting peer dependency: eslint@3.19.0
> npm ERR! node_modules/eslint
> npm ERR!   peer eslint@"^3.0.0" from eslint-config-fbjs-opensource@1.0.0
> npm ERR!   node_modules/eslint-config-fbjs-opensource
> npm ERR!     dev eslint-config-fbjs-opensource@"1.0.0" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR! See C:\Users\<user>\AppData\Local\npm-cache\eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\<user>\AppData\Local\npm-cache\_logs\2022-12-02T02_37_44_862Z-debug-0.log
> ```
> 
> So it looks like that upgrade was only possible from the `node-keytar` branch. @mauricioszabo whats the possibility of merging that whole branch with `master` here? Otherwise I'll try to take a look at what changes actually made this possible

For me locally `npm install --legacy-peer-deps` solved this as well as the output suggests.

**Comment by confused-Techie** [comment]
@benonymus Yeah was hoping to avoid that if possible, to see if there was a cleaner solution. But got those updates pushed, and so far the tests are looking good. Is this everything needed from your original PR?

**Pull request merged**
