### PR TITLE
Fix Less Syntax

### PR DESCRIPTION
**Pull request by confused-Techie**
This PR a conjoined effort of myself and @DeeDeeG resolves the issues in our style sheets for this package, that are now causing breakage after the Pulsar v1.107.0 release.

When/If merged, an update of this repo within Pulsar should constitute a hotfix release, to ensure end users are not effected

### CODE REVIEW

**Review by DeeDeeG — APPROVED** [review]
Changes appear to be exactly as intended: Adding parentheses around uncontained / non-parentheses-bound instances of math (especially/most pressingly the division `/` operation).

This is for compatibility with Less 4.x, which required this change. It should be totally back-compatible with older Less, since these parentheses were always _allowed_ before, they are only just now being _required_ to reduce ambiguity with other recent web platform features, if I recall correctly.

In looking over all the files as fast as I could while being thorough, I did not notice any syntax errors.

Furthermore, when using Pulsar to do a "Find in Project" search in this repo locally, under the `styles/` subdir, with this regex `(?<!\/)\/[^\/\n]` provided by @asiloisad on the Discord (thanks!!), I can see that all instances of division `/` are in parentheses now.

Great! 👍

**Comment by DeeDeeG** [comment]
As always... CI failing is unrelated to these changes. CI was not set up in a working fashion since the fork from upstream. So, I will be ignoring the results of CI.

I note that there are no "green"/passing runs in this forked repo as of yet.

**Comment by confused-Techie** [comment]
Yeah, might be good to give some love here soon, to find out why the CI is so unhappy, may or may not be related to the several GraphQL updates from the github actions waiting around in this repo

**Comment by DeeDeeG** [comment]
Before (broken in Pulsar v1.107.0): 

github package with not very good spacing between elements

After (With fix):

github package with better spacing between elements

**Pull request merged**
