### PR TITLE
Bump dugite

### PR DESCRIPTION
**Pull request by benonymus**
### Description of the Change

In order to support Apple silicon I updated the dugite node_module.
I went as far as possible without breaking changes.

### Applicable Issues

Github integration does not work in Apple silicon builds

### CODE REVIEW

**Comment by mauricioszabo** [comment]
Sorry for the wait - can you bump `package-lock.json` too? So the tests can run too

**Comment by confused-Techie** [comment]
@mauricioszabo @benonymus it looks like the testing is trying to use the old workflow. Maybe I can submit another PR to use our current testing platform and use that on here instead? Just so that everything can actually run properly and test against Pulsar rather than Atom?

**Comment by benonymus** [comment]
I ran into some issue with mk-snapshot while I was running `npm install`. This additional version upgrade aims to fix that. https://github.com/electron/mksnapshot/releases/tag/v11.0.1

**Comment by benonymus** [comment]
@conf

> @mauricioszabo @benonymus it looks like the testing is trying to use the old workflow. Maybe I can submit another PR to use our current testing platform and use that on here instead? Just so that everything can actually run properly and test against Pulsar rather than Atom?

Feel free to push here!

**Comment by benonymus** [comment]
We could go up to latest if we are ok dropping support for node 12: https://github.com/desktop/dugite/releases/tag/v2.0.0

**Comment by mauricioszabo** [comment]
@benonymus we're already on Electron 12, that's already Node 14, so I see no problems dropping support for node 12

**Review by confused-Techie — DISMISSED** [review]
Depending on how tests run this looks great to me, and I say lets merge it

**Comment by confused-Techie** [comment]
I know this PR is pretty old, but @benonymus would you mind taking a look at getting the lock file in sync? Or with your permission may I work off this branch to see if I can help find a resolution

**Comment by benonymus** [comment]
> I know this PR is pretty old, but @benonymus would you mind taking a look at getting the lock file in sync? Or with your permission may I work off this branch to see if I can help find a resolution

Hey, I thought I already did that. Or did I miss anything?

**Comment by confused-Techie** [comment]
> > I know this PR is pretty old, but @benonymus would you mind taking a look at getting the lock file in sync? Or with your permission may I work off this branch to see if I can help find a resolution
> 
> Hey, I thought I already did that. Or did I miss anything?

Yeah I thought we had covered it to, but I was just looking at the CI results when I commented that originally

**Comment by benonymus** [comment]
Oh I just checked the CI, I assumed it is just broken. I will try to take a look at this.

**Comment by benonymus** [comment]
> @benonymus so was just looking at this again today. And sorry seems GitHub wants to keep asking for approval to run workflows on this PR. So I've run them again.
> 
> I'm also wondering though, now we do get the tests to build everything properly, but then fail during installation, but I don't think this is because of your PR. This repo is still using the old Atom Action for testing. Which even according to [Atom](https://github.com/atom/atom/pull/25693) their aren't stable enough to continue running.
> 
> So I'm going to hope that you are good here, but will make a PR when I get home today to add the proper testing onto this repo. Then from there you could cherry pick or rebase if you'd like. I'll ping you when I've gotten that up.
> 
> But I know I mentioned this before, just getting refamiliarized with our situation over here.
> 
> Thanks again for all the effort

Sure, thanks for the update!
Let me know when you are ready!

**Comment by confused-Techie** [comment]
@benonymus I've just added the commit to the main branch. If you wanna rebase or cherry-pick it that'd be awesome. Then hopefully that can clear up whatever test weirdness we are getting

**Review by confused-Techie — APPROVED** [review]
This change looks good to me. All our tests are passing with the expected results, and hopefully with the changes to dugite we can have better mac performance overall.

**Comment by mauricioszabo** [comment]
The failure seems a flaky test, so I say, let's merge it! :)

**Pull request merged**
