### PR TITLE
rebrand git-tab-view

### PR DESCRIPTION
**Pull request by icecream17**
stumbled on this
image

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Thanks for this.

Not sure if we want to do `atom?.branding?.name ?? 'Pulsar'` again, like we did in PR https://github.com/pulsar-edit/github/pull/13 ([diff](https://github.com/pulsar-edit/github/pull/13/files#diff-83d5eff7e322a6824643933b16f5dcaf1d14ce87110c750478613040c842d793R96))?

But basically the branding API _should exist_ and be populated properly, whether in Pulsar, or in a compatible/properly configured Pulsar fork (hypothetically). So we don't necessarily have to cater to e.g. Atom and Atom forks at this point, which doesn't have the branding API in it, right?

If I hear any second opinions on this @pulsar-edit/core, then it might be interesting to figure out before we get too deep into rebranding here. But if there is no discussion / consensus I'll just say it doesn't matter a ton, these packages are first and foremost meant to work with Pulsar, not the entire possible ecosystem if supporting everything becomes hard or not worthwhile.

**Review by confused-Techie — APPROVED** [review]
The changes here look great, love seeing further usage of the rebrand API!

I say let's get it merged.

As to @DeeDeeG personally I don't think we need to worry to much about the branding API not existing properly within packages like this. Since in general we haven't. Obviously it's not a bad thing to be cautious about it, and the major benefit I could see is if anyone still works in Atom while testing changes to a package, or a user of Atom were to install our packages to keep their installation semi-updated. 

Both of which I'm sure aren't serious concerns for us. But my approval still applies if those changes are made, since they aren't wrong or incorrect, just might be more effect than they are worth once used on a large scale.

If we are worried about the branding API changing between versions of Pulsar, really I'd rather then suggest we build these considerations directly into the branding API rather than all consumers of it. But of course @icecream17 you're choice on including or excluding that recommendation

**Review by DeeDeeG — APPROVED** [review]
I would not mind some consensus on the branding API thing, but in terms of evaluating this PR itself, this is good to go IMO.

Maybe I'll move the branding topic onto Discord or a GitHub Discussion or something.

---

So, honestly if it becomes an issue with the branding API and folks urgently need our version of the github package _(instead of the version various copies of Atom still ship with out there in the wild (why would they need our version?) -- at which point it's our prerogative whether to worry about helping them or politely say "sorry this is a Pulsar package" or what have you)_...

In any case its pretty easy to code search for `atom.branding` and deal with the various uses. I think you could literally project find and replace `atom.branding.name` --> `atom?.branding?.name ?? 'Pulsar'` and expect the result to be drop-in 100% compatible.

**Review by Meadowsys — APPROVED** [review]
hehe, looks okay to me

About checking for branding API... I don't think it hurts to put it in? Best case its never needed, and its a few extra bytes in the source code. Worst case it hits an edge case someday that no one anticipated, and it saves itself.

**Pull request merged**
